/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Herramientas.PropertiesIO;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author fberrocalm
 */
public class FrmTiemposEjecucion extends javax.swing.JFrame {

    //URL ruta = this.getClass().getResource("/Config/config.properties");
    Properties prop = new Properties();
    File ruta = new File("etc/config.properties");

    /**
     * Creates new form FrmTiemposEjecucion
     */
    public FrmTiemposEjecucion() {
        initComponents();
        this.setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
        try {
            prop = PropertiesIO.read(ruta);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error durante la carga del archivo de propiedades: " + ex);
        }
        txt_Tagilis.setText("" + (Integer.parseInt(prop.getProperty("timeAgilis")) / 1000));
        txt_TWinsis.setText("" + (Integer.parseInt(prop.getProperty("timeWinsislab")) / 1000));
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Tagilis = new javax.swing.JTextField();
        txt_TWinsis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_edit = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración de tiempos de ejecución de intercambio de datos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 26, 135));
        jLabel1.setText("Configuración tiempos de intercambio de datos");

        jLabel2.setText("Tiempo establecido para intercambio de datos Agilis -> Winsislab:");

        jLabel3.setText("Tiempo establecido para intercambio de datos Winsislab -> Agilis:");

        txt_Tagilis.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_Tagilis.setEnabled(false);

        txt_TWinsis.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_TWinsis.setEnabled(false);

        jLabel4.setText("Los tiempos de ejecución se manejan con su medida en segundos");

        jLabel5.setText("Segundos");

        jLabel6.setText("Segundos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_Tagilis, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_TWinsis, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabel1))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Tagilis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TWinsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utiles/Edit.png"))); // NOI18N
        btn_edit.setText("Editar");
        btn_edit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        btn_edit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_editKeyPressed(evt);
            }
        });

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utiles/ACEPTAR1.png"))); // NOI18N
        btn_save.setText("Guardar cambios");
        btn_save.setEnabled(false);
        btn_save.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        btn_save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_saveKeyPressed(evt);
            }
        });

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utiles/CANCELAR.png"))); // NOI18N
        btn_exit.setText("Salir");
        btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        btn_exit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_exitKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_edit)
                    .addComponent(btn_save)
                    .addComponent(btn_exit))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_edit, btn_exit, btn_save});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        if (txt_TWinsis.isEnabled()) {
            txt_TWinsis.setEnabled(false);
            txt_Tagilis.setEnabled(false);
            btn_save.setEnabled(false);
        } else {
            txt_TWinsis.setEnabled(true);
            txt_Tagilis.setEnabled(true);
            btn_save.setEnabled(true);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_editKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_editKeyPressed
        // TODO add your handling code here:
        if (txt_TWinsis.isEnabled()) {
            txt_TWinsis.setEnabled(false);
            txt_Tagilis.setEnabled(false);
            btn_save.setEnabled(false);
        } else {
            txt_TWinsis.setEnabled(true);
            txt_Tagilis.setEnabled(true);
            btn_save.setEnabled(true);
        }
    }//GEN-LAST:event_btn_editKeyPressed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_exitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_exitKeyPressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_exitKeyPressed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(this, "Se dispone a modificar datos de tiempos\na de intercambio de información entre\nlas bases de datos del sistema \n"
                + "¿desea continuar?", "Cambio de tiempos de ejecución", JOptionPane.OK_CANCEL_OPTION);
        if (JOptionPane.OK_OPTION == op) {
            op = JOptionPane.showConfirmDialog(this, "Confirme, ¿Desea hacer permanentes los cambios?"
                    + "¿desea continuar?", "Cambio de tiempos de ejecución", JOptionPane.OK_CANCEL_OPTION);
            if (JOptionPane.OK_OPTION == op) {
                if (txt_TWinsis.getText().isEmpty() || txt_Tagilis.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Debe ingresar los nuevos tiempos\nde ejecución para el intercambio de datos");
                } else {
                    prop.setProperty("timeAgilis", String.valueOf(Integer.parseInt(txt_Tagilis.getText()) * 1000));
                    prop.setProperty("timeWinsislab", String.valueOf(Integer.parseInt(txt_TWinsis.getText()) * 1000));
                    try {
                        PropertiesIO.write(prop, ruta);
                        JOptionPane.showMessageDialog(null, "Guardado");
                        btn_save.setEnabled(false);
                        txt_TWinsis.setEnabled(false);
                        txt_Tagilis.setEnabled(false);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Ocurrió el siguiente problema al\nmodificar el archivo config.properties:\n" + ex.getMessage());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Se canceló el proceso de cambio de tiempos");
                btn_save.setEnabled(false);
                txt_Tagilis.setText("" + (Integer.parseInt(prop.getProperty("timeAgilis")) / 1000));
                txt_TWinsis.setText("" + (Integer.parseInt(prop.getProperty("timeWinsislab")) / 1000));
                txt_TWinsis.setEnabled(false);
                txt_Tagilis.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Se canceló el proceso de cambio de tiempos");
            btn_save.setEnabled(false);
            txt_Tagilis.setText("" + (Integer.parseInt(prop.getProperty("timeAgilis")) / 1000));
            txt_TWinsis.setText("" + (Integer.parseInt(prop.getProperty("timeWinsislab")) / 1000));
            txt_TWinsis.setEnabled(false);
            txt_Tagilis.setEnabled(false);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_saveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_saveKeyPressed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(this, "Se dispone a modificar datos de tiempos\na de intercambio de información entre\nlas bases de datos del sistema \n"
                + "¿desea continuar?", "Cambio de tiempos de ejecución", JOptionPane.OK_CANCEL_OPTION);
        if (JOptionPane.OK_OPTION == op) {
            op = JOptionPane.showConfirmDialog(this, "Confirme, ¿Desea hacer permanentes los cambios?"
                    + "¿desea continuar?", "Cambio de tiempos de ejecución", JOptionPane.OK_CANCEL_OPTION);
            if (JOptionPane.OK_OPTION == op) {
                if (txt_TWinsis.getText().isEmpty() || txt_Tagilis.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Debe ingresar los nuevos tiempos\nde ejecución para el intercambio de datos");
                } else {
                    prop.setProperty("timeAgilis", String.valueOf(Integer.parseInt(txt_Tagilis.getText()) * 1000));
                    prop.setProperty("timeWinsislab", String.valueOf(Integer.parseInt(txt_TWinsis.getText()) * 1000));
                    try {
                        PropertiesIO.write(prop, ruta);
                        JOptionPane.showMessageDialog(null, "Guardado");
                        btn_save.setEnabled(false);
                        txt_TWinsis.setEnabled(false);
                        txt_Tagilis.setEnabled(false);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Ocurrió el siguiente problema al\nmodificar el archivo config.properties:\n" + ex.getMessage());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Se canceló el proceso de cambio de tiempos");
                btn_save.setEnabled(false);
                txt_Tagilis.setText("" + (Integer.parseInt(prop.getProperty("timeAgilis")) / 1000));
                txt_TWinsis.setText("" + (Integer.parseInt(prop.getProperty("timeWinsislab")) / 1000));
                txt_TWinsis.setEnabled(false);
                txt_Tagilis.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Se canceló el proceso de cambio de tiempos");
            btn_save.setEnabled(false);
            txt_Tagilis.setText("" + (Integer.parseInt(prop.getProperty("timeAgilis")) / 1000));
            txt_TWinsis.setText("" + (Integer.parseInt(prop.getProperty("timeWinsislab")) / 1000));
            txt_TWinsis.setEnabled(false);
            txt_Tagilis.setEnabled(false);
        }
    }//GEN-LAST:event_btn_saveKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_TWinsis;
    private javax.swing.JTextField txt_Tagilis;
    // End of variables declaration//GEN-END:variables
///ESTABLECE LA IMAGEN O LOGO DE LA APP EN LA BARRA DE LOS FORMULARIOS

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Utiles/FORMULARIOS.png"));
        return retValue;
    }

}
