/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controler.controladorBD_generico;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author fberrocalm
 */
public class ListaExamenes extends javax.swing.JFrame {

    String idWinsislab;
    controladorBD_generico controlBD;
    Connection con;

    /**
     * Creates new form ListaExamenes
     *
     * @param c
     */
    public ListaExamenes(Connection c) {
        initComponents();
        con = c;
        controlBD = new controladorBD_generico();
        tab_examenes.setModel(controlBD.listadoTablaExamenes(con));
        this.setLocationRelativeTo(null);
        this.setIconImage(getIconImage());
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_examenes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_seleccion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cb_filtro = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        btn_filtro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado de Laboratorios Winsislab");

        tab_examenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_examenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tab_examenesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tab_examenes);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_seleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utiles/OK1.png"))); // NOI18N
        btn_seleccion.setText("Elegir");
        btn_seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionActionPerformed(evt);
            }
        });
        btn_seleccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_seleccionKeyPressed(evt);
            }
        });

        jLabel7.setText("Filtrar por:");

        cb_filtro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "examen_cod", "cod_fact", "nombre", "nemonico" }));
        cb_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_filtroActionPerformed(evt);
            }
        });

        jTextField1.setText("%");
        jTextField1.setEnabled(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        btn_filtro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utiles/NoFiltra.png"))); // NOI18N
        btn_filtro.setText("Quitar filtro");
        btn_filtro.setEnabled(false);
        btn_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtroActionPerformed(evt);
            }
        });
        btn_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_filtroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_filtro)
                .addGap(664, 664, 664)
                .addComponent(btn_seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cb_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_filtro))
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de laboratorios existentes en Winsislab", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_examenesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_examenesMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            btn_seleccion.doClick();
        }
    }//GEN-LAST:event_tab_examenesMousePressed

    private void btn_seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionActionPerformed
        // TODO add your handling code here:
        retorno();
        this.dispose();
    }//GEN-LAST:event_btn_seleccionActionPerformed

    private void btn_seleccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_seleccionKeyPressed
        // TODO add your handling code here:
        retorno();
        this.dispose();
    }//GEN-LAST:event_btn_seleccionKeyPressed

    private void cb_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_filtroActionPerformed
        if (String.valueOf(cb_filtro.getSelectedItem()).equals(" ") && !btn_filtro.isEnabled()) {
            JOptionPane.showMessageDialog(null, "Seleccione un criterio para Filtrar");
        } else {
            jTextField1.setText(null);
            jTextField1.setEnabled(true);
            jTextField1.setText("%");
            jTextField1.requestFocus();
            btn_filtro.setEnabled(true);
        }
    }//GEN-LAST:event_cb_filtroActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        tab_examenes.setModel(controlBD.filtrolistadoTablaExamenes(con, jTextField1.getText(), String.valueOf(cb_filtro.getSelectedItem())));
        tab_examenes.getColumn("Nombre").setPreferredWidth(600);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void btn_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtroActionPerformed
        // TODO add your handling code here:
        if (jTextField1.isEnabled()) {
            cb_filtro.setSelectedIndex(0);
            jTextField1.setText(null);
            jTextField1.setEnabled(false);
            tab_examenes.setModel(controlBD.listadoTablaExamenes(con));
            tab_examenes.getColumn("Nombre").setPreferredWidth(600);
            btn_filtro.setEnabled(false);
        }
    }//GEN-LAST:event_btn_filtroActionPerformed

    private void btn_filtroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_filtroKeyPressed
        // TODO add your handling code here:
        if (jTextField1.isEnabled()) {
            cb_filtro.setSelectedIndex(0);
            jTextField1.setText(null);
            jTextField1.setEnabled(false);
            tab_examenes.setModel(controlBD.listadoTablaExamenes(con));
            tab_examenes.getColumn("Nombre").setPreferredWidth(600);
            btn_filtro.setEnabled(false);
        }
    }//GEN-LAST:event_btn_filtroKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_filtro;
    private javax.swing.JButton btn_seleccion;
    private javax.swing.JComboBox cb_filtro;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tab_examenes;
    // End of variables declaration//GEN-END:variables

    public void retorno() {
        if (tab_examenes.getSelectedColumn() != -1) {
            idWinsislab = String.valueOf(tab_examenes.getValueAt(tab_examenes.getSelectedRow(), 0));
            HomologacionHexamenes.txt_idwinsislab.setText(idWinsislab);
        } else {
            idWinsislab = null;
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Utiles/listado.png"));
        return retValue;
    }

}
