package view;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JRootPane;

public class SplashFrame extends javax.swing.JFrame {

    //esta variable hace referencia a si misma
    private final SplashFrame splashFrame = this;

    /**
     * Creates new form SplashFrame
     */
    public SplashFrame() {
        //Este metodo hace que el frame no tenga la barra de titulo
        //debe ser llamado antes de cargar los componentes de frame
        //en este caso antes del initComponents
        setUndecorated(true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
        //hace la ventana transparente 1 es totalmente visible, 0 es totalmente invisible
        AWTUtilities.setWindowOpacity(splashFrame, new Float(0.85));
        //centro el frame a la pantalla
        setLocationRelativeTo(null);
        startThread();
        this.getRootPane().setBackground(Color.WHITE);
    }

    private void startThread() {
        Thread thread = new Thread(new Runnable() {

            public void run() {
                //se envia el frame del splash a la aplicacion que deseamos abrir
                FrmLogin aplicationFrame = new FrmLogin(splashFrame);
                //centro el frame
                aplicationFrame.setLocationRelativeTo(null);
                //hago el frame visible
                aplicationFrame.setVisible(true);
                //cuando set termita de instanciar el FrmLogin el SplashFrame se cierra
                dispose();
            }
        });
        thread.start();
    }

    public JProgressBar getProgressBar() {
        //este metodo nos permite obtener la barra de progreso desde el FrmLogin
        return progressBar;
    }

    public JLabel getLabel() {
        //este metodo devuelve el label
        return label2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        label2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressBar.setFont(new java.awt.Font("Tahoma", 0, 6)); // NOI18N
        progressBar.setForeground(new java.awt.Color(0, 26, 135));
        progressBar.setStringPainted(true);
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 10));

        label2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 255));
        label2.setText("Loading Information");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utiles/BASEDATOS.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label2;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Utiles/FORMULARIOS.png"));
        return retValue;
    }
}
